"""initial revision

Revision ID: f1f2cee972cb
Revises:
Create Date: 2026-04-08 13:08:37.238730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f1f2cee972cb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "missions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name", sa.String(length=128), server_default="", nullable=False
        ),
        sa.Column(
            "description",
            sa.String(length=128),
            server_default="",
            nullable=False,
        ),
        sa.Column(
            "duration", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "reward_money", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "reward_influence",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "difficulty",
            sa.Enum("MissionDifficulty", native_enum=False, length=32),
            server_default="easy",
            nullable=False,
        ),
        sa.Column("slots", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "power_required", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "intellect_required",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "agility_required",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default="NOW()", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True
    )
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "THUG",
                "HACKER",
                "NEGOTIATOR",
                name="characterrole",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "trait",
            sa.Enum(
                "HOT",
                "QUIET",
                "GREEDY",
                name="charactertrait",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("power", sa.Integer(), nullable=False),
        sa.Column("agility", sa.Integer(), nullable=False),
        sa.Column("intellect", sa.Integer(), nullable=False),
        sa.Column("loyalty", sa.Integer(), nullable=False),
        sa.Column("is_busy", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_characters_user_id"), "characters", ["user_id"], unique=False
    )
    op.create_table(
        "mission_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mission_id", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "POLICE_RAID",
                "COMPETITOR_ATTACK",
                "RANDOM_LUCK",
                name="missioneventtype",
            ),
            nullable=False,
        ),
        sa.Column("chance", sa.Integer(), server_default="10", nullable=False),
        sa.Column(
            "description", sa.String(), server_default="", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_missions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("mission_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCESS",
                "FAILED",
                name="missionstatus",
                native_enum=False,
                length=32,
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=False),
        sa.Column("success_chance", sa.Integer(), nullable=False),
        sa.Column("result_reward", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_missions_user_id"),
        "user_missions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("money", sa.Integer(), nullable=False),
        sa.Column("influence", sa.Integer(), nullable=False),
        sa.Column("wanted_level", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "mission_characters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_mission_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("slot_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_mission_id"],
            ["user_missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mission_characters_character_id"),
        "mission_characters",
        ["character_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mission_characters_user_mission_id"),
        "mission_characters",
        ["user_mission_id"],
        unique=False,
    )
    op.create_table(
        "tools",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("bonus_intellect", sa.Integer(), nullable=False),
        sa.Column("bonus_agility", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["characters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weapons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("bonus_power", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["characters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weapons")
    op.drop_table("tools")
    op.drop_index(
        op.f("ix_mission_characters_user_mission_id"),
        table_name="mission_characters",
    )
    op.drop_index(
        op.f("ix_mission_characters_character_id"),
        table_name="mission_characters",
    )
    op.drop_table("mission_characters")
    op.drop_table("user_resources")
    op.drop_index(op.f("ix_user_missions_user_id"), table_name="user_missions")
    op.drop_table("user_missions")
    op.drop_table("mission_events")
    op.drop_index(op.f("ix_characters_user_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("missions")
    # ### end Alembic commands ###
