"""add_mission_stat_type_weapon_tool_slots_reward_fields

Revision ID: e5bc5d41e6f6
Revises: f0a1b2c3d4e5
Create Date: 2026-04-09 19:07:04.799698

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5bc5d41e6f6"
down_revision: Union[str, Sequence[str], None] = "f0a1b2c3d4e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "missions",
        sa.Column(
            "wanted_increase",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "missions",
        sa.Column(
            "mission_stat_type",
            sa.Enum(
                "FORCE",
                "STEALTH",
                "DIPLOMACY",
                name="missionstattype",
                native_enum=False,
                length=32,
            ),
            server_default="force",
            nullable=False,
        ),
    )
    op.add_column(
        "missions",
        sa.Column(
            "weapon_slots_required",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "missions",
        sa.Column(
            "tool_slots_required",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "missions",
        sa.Column(
            "reward_multiplier",
            sa.Float(),
            server_default="1.0",
            nullable=False,
        ),
    )
    op.add_column(
        "user_missions",
        sa.Column(
            "reward_money",
            sa.Integer(),
            server_default="0",
            nullable=True,
        ),
    )
    op.add_column(
        "user_missions",
        sa.Column(
            "reward_influence",
            sa.Integer(),
            server_default="0",
            nullable=True,
        ),
    )
    op.add_column(
        "user_missions",
        sa.Column(
            "wanted_increase",
            sa.Integer(),
            server_default="0",
            nullable=True,
        ),
    )
    op.drop_column("user_missions", "result_reward")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_missions",
        sa.Column(
            "result_reward",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("user_missions", "wanted_increase")
    op.drop_column("user_missions", "reward_influence")
    op.drop_column("user_missions", "reward_money")
    op.drop_column("missions", "reward_multiplier")
    op.drop_column("missions", "tool_slots_required")
    op.drop_column("missions", "weapon_slots_required")
    op.drop_column("missions", "mission_stat_type")
    op.drop_column("missions", "wanted_increase")
    # ### end Alembic commands ###
