"""add_interactive_event_system

Revision ID: 606f7e731343
Revises: e5bc5d41e6f6
Create Date: 2026-04-10 16:44:42.475619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "606f7e731343"
down_revision: Union[str, Sequence[str], None] = "e5bc5d41e6f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mission_event_choices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column(
            "choice_type",
            sa.Enum(
                "PAYOFF",
                "FIGHT",
                "TALK",
                "DO_NOTHING",
                name="eventchoicetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "label", sa.String(length=64), server_default="", nullable=False
        ),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "money_cost", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "influence_required",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "power_required", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "success_chance_base",
            sa.Integer(),
            server_default="50",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["mission_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mission_event_choices_event_id"),
        "mission_event_choices",
        ["event_id"],
        unique=False,
    )
    op.create_table(
        "user_mission_event_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_mission_id", sa.Integer(), nullable=False),
        sa.Column("event_choice_id", sa.Integer(), nullable=True),
        sa.Column(
            "chosen_type",
            sa.Enum(
                "PAYOFF",
                "FIGHT",
                "TALK",
                "DO_NOTHING",
                name="eventchoicetype",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "resolved", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("result_description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_choice_id"],
            ["mission_event_choices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_mission_id"],
            ["user_missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_mission_event_logs_user_mission_id"),
        "user_mission_event_logs",
        ["user_mission_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_mission_event_logs_user_mission_id"),
        table_name="user_mission_event_logs",
    )
    op.drop_table("user_mission_event_logs")
    op.drop_index(
        op.f("ix_mission_event_choices_event_id"),
        table_name="mission_event_choices",
    )
    op.drop_table("mission_event_choices")
    # ### end Alembic commands ###
