"""add_shop_items_table

Revision ID: 85b8255de087
Revises: add_territory_system
Create Date: 2026-04-11 12:41:18.150735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "85b8255de087"
down_revision: Union[str, Sequence[str], None] = "add_territory_system"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column(
            "item_type",
            sa.Enum(
                "CHARACTER",
                "WEAPON",
                "TOOL",
                name="shopitemtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("cost_money", sa.Integer(), nullable=False),
        sa.Column("cost_influence", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "THUG",
                "HACKER",
                "NEGOTIATOR",
                "CAPO",
                name="characterrole",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "trait",
            sa.Enum(
                "HOT",
                "QUIET",
                "GREEDY",
                name="charactertrait",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("base_power", sa.Integer(), nullable=False),
        sa.Column("base_intellect", sa.Integer(), nullable=False),
        sa.Column("base_agility", sa.Integer(), nullable=False),
        sa.Column("base_loyalty", sa.Integer(), nullable=False),
        sa.Column("bonus_power", sa.Integer(), nullable=False),
        sa.Column("bonus_intellect", sa.Integer(), nullable=False),
        sa.Column("bonus_agility", sa.Integer(), nullable=False),
        sa.Column(
            "is_available", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("buyer_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "territories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_missions",
        "mission_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "user_territories",
        "captured_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_territories",
        "captured_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_missions",
        "mission_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "territories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_table("shop_items")
    # ### end Alembic commands ###
