"""add_passive_income_tracking

Revision ID: f6a282f6fff3
Revises: add_map_fields
Create Date: 2026-04-11 14:11:08.016163

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6a282f6fff3"
down_revision: Union[str, Sequence[str], None] = "add_map_fields"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_missions",
        "started_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "user_missions",
        "ends_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "user_missions",
        "available_until",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "user_missions",
        "location_name",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.alter_column(
        "user_missions",
        "position_x",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "user_missions",
        "position_y",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.add_column(
        "user_resources",
        sa.Column(
            "last_income_tick",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "user_resources",
        sa.Column(
            "active_playtime_minutes",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_resources", "active_playtime_minutes")
    op.drop_column("user_resources", "last_income_tick")
    op.alter_column(
        "user_missions",
        "position_y",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "user_missions",
        "position_x",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "user_missions",
        "location_name",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )
    op.alter_column(
        "user_missions",
        "available_until",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "user_missions",
        "ends_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "user_missions",
        "started_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # ### end Alembic commands ###
