services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: mafia
      POSTGRES_USER: krushovice
      POSTGRES_PASSWORD: 9874123Kr
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
       - "5050:80"

  api:
    build:
      context: .
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    environment:
      - APP_CONFIG__DB__URL=postgresql+asyncpg://krushovice:9874123Kr@pg:5432/mafia
      - APP_CONFIG__TMA__ENABLED=true
      - APP_CONFIG__TMA__BOT_TOKEN=${BOT_TELEGRAM_TOKEN}
      - APP_CONFIG__TMA__URL=${TMA_URL:-http://localhost:3000}
      # BOT vars moved to local bot run to bypass TG blocking in container
      # - BOT_TELEGRAM_TOKEN=${BOT_TELEGRAM_TOKEN}
      # - BOT_WEBHOOK_URL=${BOT_WEBHOOK_URL:-}
      # - BOT_API_URL=http://api:8000
      # - BOT_TMA_URL=${TMA_URL:-http://localhost:3000}
    ports:
      - "8000:8000"
    depends_on:
      - pg
